version: "3.8"

services:
  nginx:
    ports:
      - "4001:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - db


  php:
    build: ./php
    volumes:
      - ./www:/var/www/html
    depends_on:
    - db


  db:
    environment: 
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  phpmyadmin:
    ports:
      - "6001:80"
    environment:
      PMA_HOST: db
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend:

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
